name: bottom_nav_bar
description: A new Flutter package project.
version: 0.0.1
homepage: https://github.com/artplaygamesofc/bottom_nav_bar.git
repository: https://github.com/artplaygamesofc/bottom_nav_bar.git

environment:
  sdk: '>=3.2.0 <4.0.0'
  flutter: 3.27.0

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
